<?php
declare(strict_types=1);

namespace WebLoader\Test\Filter;

use PHPUnit\Framework\TestCase;
use WebLoader\Filter\PHPCoffeeScriptFilter;

/**
 * CompilerTest
 *
 * @author Jan Svantner
 */
class PHPCoffeeScriptFilterTest extends TestCase
{

	/** @var PHPCoffeeScriptFilter */
	private $object;


	protected function setUp(): void
	{
		$this->object = new PHPCoffeeScriptFilter();
	}


	public function testSimpleLoadAndParse(): void
	{
		if (!class_exists('CoffeeScript\Compiler')) {
			$this->markTestSkipped('Missing CoffeeScript compiler.');
		}

		$compiler = new PHPCoffeeScriptFilter();
		$coffee = $compiler->compileCoffee('number = -42 if opposite', null);

		$version = COFFEESCRIPT_VERSION;
		$expected = <<<COFFEE
// Generated by CoffeeScript PHP {$version}
(function() {
  var number;

  if (opposite) {
    number = -42;
  }

}).call(this);

COFFEE;
		$this->assertEquals($expected, $coffee);
	}
}
